[FE]写真を複数枚表示できるよう変更
nagayamajun/fillhome-web pull request #14
Opened 2023-10-22 10:26 UTC by nagayamajun

###概要
写真が複数枚表示できるようにしました。

2023-10-22 12:23 UTC, nagayamajun commented on package.json
>      "@hookform/resolvers": "^3.3.1",
splidejsの導入をしました。

記事がある程度あり、実装しやすい点
多くのユーザーに使われているライブラリ
依存関係が小さい

2023-10-23 06:33 UTC, nagayamajun commented
widthが画面幅によって変わると写真の大きさが変わってしまうのが嫌だったのでスマホサイズとPCサイズ(ギリタブレットも対応できるぐらい)に変更しました。
sm以上は固定値の幅でsm以下の時はw-90%で可動的にしています！

[画面収録 2023-10-23 15.26.35 2.mov.zip](https://github.com/nagayamajun/fillhome-web/files/13066844/2023-10-23.15.26.35.2.mov.zip)

2023-10-24 05:16 UTC, nagayamajun commented
@ponsAoki 
お手隙の際にご確認よろしくお願いします🙇

2023-10-24 05:49 UTC, ponsAoki approved these changes
@nagayamajun 
LGTMです！
1つ気になったことだけコメントしてるのでご確認お願いします！

2023-10-24 05:49 UTC, ponsAoki commented on src/feature/room/components/admin-list/components/AdminRentalHouseInfo/index.tsx
> +          <SplideSlide key={index} >
自分が見逃してるだけかもしれないんですが、これってアニメーションの詳細 (動きの秒数とか間隔とか？) ってどこかにパラメータで設定しているわけではないんですかね？詳細は何も書いてなくてデフォルトのパラメータの値で動いているみたいな感じなんですかね？

2023-10-24 05:50 UTC, ponsAoki requested changes
@nagayamajun 
すみません、コンフリクトの解消だけお願いします🙏

2023-10-24 06:19 UTC, nagayamajun commented on src/feature/room/components/admin-list/components/AdminRentalHouseInfo/index.tsx
> +          <SplideSlide key={index} >
@ponsAoki 
コメントありがとうございます🙇
その認識です！細かいルールをつけても良かったのですがデザイン案も固まっていないので今回はデフォルト値を利用しました！

2023-10-24 06:20 UTC, nagayamajun commented on src/feature/room/components/admin-list/components/AdminRentalHouseInfo/index.tsx
> +import '@splidejs/react-splide/css';
ここでデフォルト値を当てています

2023-10-25 18:02 UTC, ponsAoki commented
@nagayamajun 
問題ないと思うんでマージしますねー！3分後くらいに

2023-10-25 18:19 UTC, merged